"""Random, always solvable maps: ``flyin generate``.

A grid of zones with random types and capacities, connected to their
right and lower neighbours (some connections left out), or zones
scattered at random and linked to their nearest neighbours. The same seed
always gives the same map, so a map can be shared by its seed.
"""

import random

from .bounds import lower_bound
from .mapfile import has_route, parse_map

KINDS = ("normal",) * 6 + ("priority", "restricted", "blocked")


def generate(seed: int, width: int = 6, height: int = 3,
             drones: int = 10, shape: str = "grid") -> str:
    """Return the text of a solvable map for ``seed``.

    Args:
        seed: Any integer; the same seed gives the same map.
        width: Zones per row (at least 2); for ``random``: the map has
            ``width * height`` zones.
        height: Rows (at least 1).
        drones: Number of drones.
        shape: ``grid`` (neighbours right and below) or ``random``
            (zones scattered, each linked to its nearest neighbours).
    """
    rng = random.Random(seed)
    width, height = max(2, width), max(1, height)
    build = _scatter if shape == "random" else _attempt
    for _ in range(1000):
        text = build(rng, seed, width, height, max(1, drones))
        fly_map = parse_map(text)
        if has_route(fly_map):
            bound = lower_bound(fly_map)
            return text.replace("# lower bound: ?",
                                f"# lower bound: {bound} turns")
    raise ValueError("could not build a solvable map, try another seed")


def _attempt(rng: random.Random, seed: int, width: int, height: int,
             drones: int) -> str:
    """Build one random grid (it may have no route)."""
    start = (0, rng.randrange(height))
    end = (width - 1, rng.randrange(height))
    lines = [f"# generated by flyin: seed {seed}, {width}x{height} grid",
             "# lower bound: ?", f"nb_drones: {drones}", ""]
    for x in range(width):
        for y in range(height):
            name = f"z{x}_{y}"
            if (x, y) == start:
                lines.append(f"start_hub: {name} {x} {y} [color=green]")
            elif (x, y) == end:
                lines.append(f"end_hub: {name} {x} {y} [color=yellow]")
            else:
                kind = rng.choice(KINDS)
                lines.append(f"hub: {name} {x} {y} [zone={kind} "
                             f"max_drones={rng.randint(1, 3)}]")
    lines.append("")
    for x in range(width):
        for y in range(height):
            for nx, ny in ((x + 1, y), (x, y + 1)):
                if nx < width and ny < height and rng.random() < 0.8:
                    lines.append(f"connection: z{x}_{y}-z{nx}_{ny} "
                                 f"[max_link_capacity={rng.randint(1, 3)}]")
    return "\n".join(lines) + "\n"


def _scatter(rng: random.Random, seed: int, width: int, height: int,
             drones: int) -> str:
    """Scatter zones on a plane and link each to its 2-3 nearest ones.

    The start is the leftmost zone, the end the rightmost one.
    """
    count = width * height
    points: list[tuple[int, int]] = []
    while len(points) < count:
        point = (rng.randrange(width * 4), rng.randrange(height * 4))
        if point not in points:
            points.append(point)
    points.sort()
    names = [f"n{i}" for i in range(count)]
    lines = [f"# generated by flyin: seed {seed}, {count} scattered zones",
             "# lower bound: ?", f"nb_drones: {drones}", ""]
    for index, (name, (x, y)) in enumerate(zip(names, points)):
        if index == 0:
            lines.append(f"start_hub: {name} {x} {y} [color=green]")
        elif index == count - 1:
            lines.append(f"end_hub: {name} {x} {y} [color=yellow]")
        else:
            lines.append(f"hub: {name} {x} {y} [zone={rng.choice(KINDS)} "
                         f"max_drones={rng.randint(1, 3)}]")
    lines.append("")
    links: set[tuple[int, int]] = set()
    for i, (x, y) in enumerate(points):
        nearest = sorted(range(count), key=lambda j: (points[j][0] - x) ** 2
                         + (points[j][1] - y) ** 2)[1:rng.randint(3, 4)]
        links.update((min(i, j), max(i, j)) for j in nearest)
    for i, j in sorted(links):
        lines.append(f"connection: {names[i]}-{names[j]} "
                     f"[max_link_capacity={rng.randint(1, 3)}]")
    return "\n".join(lines) + "\n"
