"""Random, always solvable maps: ``flyin generate``.

A grid of zones with random types and capacities, connected to their
right and lower neighbours (some connections left out). The same seed
always gives the same map, so a map can be shared by its seed.
"""

import random

from .bounds import lower_bound
from .mapfile import has_route, parse_map

KINDS = ("normal",) * 6 + ("priority", "restricted", "blocked")


def generate(seed: int, width: int = 6, height: int = 3,
             drones: int = 10) -> str:
    """Return the text of a solvable map for ``seed``.

    Args:
        seed: Any integer; the same seed gives the same map.
        width: Zones per row (at least 2).
        height: Rows (at least 1).
        drones: Number of drones.
    """
    rng = random.Random(seed)
    width, height = max(2, width), max(1, height)
    for _ in range(1000):
        text = _attempt(rng, seed, width, height, max(1, drones))
        fly_map = parse_map(text)
        if has_route(fly_map):
            bound = lower_bound(fly_map)
            return text.replace("# lower bound: ?",
                                f"# lower bound: {bound} turns")
    raise ValueError("could not build a solvable map, try another seed")


def _attempt(rng: random.Random, seed: int, width: int, height: int,
             drones: int) -> str:
    """Build one random grid (it may have no route)."""
    start = (0, rng.randrange(height))
    end = (width - 1, rng.randrange(height))
    lines = [f"# generated by flyin: seed {seed}, {width}x{height} grid",
             "# lower bound: ?", f"nb_drones: {drones}", ""]
    for x in range(width):
        for y in range(height):
            name = f"z{x}_{y}"
            if (x, y) == start:
                lines.append(f"start_hub: {name} {x} {y} [color=green]")
            elif (x, y) == end:
                lines.append(f"end_hub: {name} {x} {y} [color=yellow]")
            else:
                kind = rng.choice(KINDS)
                lines.append(f"hub: {name} {x} {y} [zone={kind} "
                             f"max_drones={rng.randint(1, 3)}]")
    lines.append("")
    for x in range(width):
        for y in range(height):
            for nx, ny in ((x + 1, y), (x, y + 1)):
                if nx < width and ny < height and rng.random() < 0.8:
                    lines.append(f"connection: z{x}_{y}-z{nx}_{ny} "
                                 f"[max_link_capacity={rng.randint(1, 3)}]")
    return "\n".join(lines) + "\n"
